# Generated by Django 4.2.2 on 2023-06-21 04:49

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_Us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone_no', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Phone No.')),
                ('message', models.TextField(verbose_name='Message')),
            ],
        ),
        migrations.CreateModel(
            name='Get_online_quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Full Name')),
                ('email_id', models.EmailField(max_length=254, verbose_name='Email ID')),
                ('company_name', models.CharField(max_length=300, verbose_name='Company Name')),
                ('contact_no', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Contact No')),
                ('product_name', models.CharField(max_length=300, verbose_name='Product Name')),
                ('chemical_name', models.CharField(max_length=300, verbose_name='Chemical Name')),
                ('cas_number', models.CharField(max_length=300, verbose_name='CAS No.')),
                ('structure', models.ImageField(blank=True, null=True, upload_to='online_quote')),
                ('quantity', models.CharField(max_length=60, verbose_name='Quantity')),
                ('generated_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_name', models.CharField(max_length=255, verbose_name='Category Name')),
                ('category_slug', autoslug.fields.AutoSlugField(editable=False, populate_from='Category_name', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RFQ_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('ordered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Impurity_Chemicals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=300, unique=True, verbose_name='Product Name')),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('cat_no', models.CharField(default='N.A.', max_length=300, verbose_name='Cat No.')),
                ('chemical_name', models.CharField(default='N.A.', max_length=300, verbose_name='Chemical Name')),
                ('molecular_formula', models.CharField(default='N.A.', max_length=300, verbose_name='Molecular Formula')),
                ('molecular_weight', models.DecimalField(decimal_places=10, max_digits=10, verbose_name='Molecular Weight')),
                ('cas_number', models.CharField(max_length=300, verbose_name='CAS Number')),
                ('solubility', models.CharField(default='N.A.', max_length=300, verbose_name='Solubility')),
                ('storage', models.CharField(default='N.A.', max_length=300, verbose_name='Storage')),
                ('keywords', models.CharField(default='N.A.', max_length=300, verbose_name='Keywords')),
                ('purity_by_HPLC', models.DecimalField(decimal_places=10, max_digits=10, verbose_name='Purity by HPLC')),
                ('slug_id', autoslug.fields.AutoSlugField(editable=False, populate_from='product_name', unique=True)),
                ('inventory_status', models.CharField(default='In Stock', max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.product_category')),
            ],
        ),
    ]
