# Generated by Django 4.2.2 on 2023-06-21 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_contact_us_get_online_quote_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impurity_chemicals',
            name='molecular_weight',
            field=models.CharField(max_length=100, null=True, verbose_name='Molecular Weight'),
        ),
        migrations.AlterField(
            model_name='impurity_chemicals',
            name='purity_by_HPLC',
            field=models.CharField(max_length=100, null=True, verbose_name='Purity by HPLC'),
        ),
    ]
