# Generated by Django 4.2.2 on 2023-07-18 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_alter_impurity_chemicals_molecular_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfq_list',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='rfq_list',
            name='quantity',
            field=models.CharField(default=1, max_length=222),
        ),
    ]
